apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: 427107249392.dkr.ecr.us-east-1.amazonaws.com/customers:1.0
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-produto
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-produto
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: cm-customer
          ports:
            - containerPort: 8080
